name: Running CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setting up apt
      run: apt update

    - name: Installing toolchain
      run: apt install build-essential ninja cmake -y

    - name: Meta/Build.sh
      run: sh Meta/Build.sh
